image_to_gridmap_demo:
  image_topic: "/map_image"
  resolution: 0.10
  map_frame_id: "map"
  min_height: -1.0
  max_height: 0.0

grid_map_visualization:
  grid_map_topic: /image_to_gridmap_demo/grid_map
  grid_map_visualizations:
    - name: elevation_points
      type: point_cloud
      params:
        layer: elevation
    - name: elevation_grid
      type: occupancy_grid
      params:
        layer: elevation
        data_min: -1.0
        data_max: -0.5
    - name: flat_grid
      type: flat_point_cloud
      params:
        height: -0.5

    - name: elevation_cells
      type: grid_cells
      params:
       layer: elevation
       lower_threshold: -1.0
       upper_threshold: -0.5
